<template>
  <main class="shell narrow"><NuxtLink class="back" to="/student">← 作业列表</NuxtLink><p class="eyebrow">作答中</p><h1>{{ detail?.title ?? '加载作业…' }}</h1>
    <p v-if="message" class="notice">{{ message }}</p>
    <section v-if="currentItem" class="card wide"><span class="tag">第 {{ currentItem.position }} 题</span><h2>{{ currentItem.prompt }}</h2><textarea v-model="answer" class="answer-input" rows="5" aria-label="答案" @input="saveDraft" /><p>同步状态：{{ syncStatus }}</p></section>
    <div class="actions"><button class="button secondary" :disabled="current === 0" @click="current = previousQuestionIndex(current)">上一题</button><button class="button secondary" :disabled="!detail || current >= detail.items.length - 1" @click="current = nextQuestionIndex(current, detail?.items.length ?? 0)">下一题</button><button class="button primary" :disabled="!online || unanswered > 0 || !canSubmit" @click="submit">提交作业</button></div><p v-if="unanswered > 0" class="notice">还有 {{ unanswered }} 题未作答</p>
  </main>
</template>
<script setup lang="ts">
import { canSubmitAttempt, flushAttempt, getSubmissionKey, queueAnswer } from '../../../lib/drafts'
import { fetchCurrentPrincipal, type CurrentPrincipal } from '../../../lib/student-api'
import { getUnansweredCount, nextQuestionIndex, previousQuestionIndex } from '../../../lib/student-workflow'
interface Item { id: string; position: number; prompt: string; answer: Record<string, unknown> | null; version: number }
interface Detail { id: string; title: string; attempt: { id: string }; items: Item[] }
const config = useRuntimeConfig(); const token = useCookie<string | null>('edu_access_token'); const route = useRoute(); const detail = ref<Detail | null>(null); const principal = ref<CurrentPrincipal | null>(null); const current = ref(0); const answer = ref(''); const syncStatus = ref('未保存'); const message = ref(''); const online = ref(process.client ? navigator.onLine : false)
const currentItem = computed(() => detail.value?.items[current.value]); const unanswered = computed(() => detail.value ? getUnansweredCount(detail.value.items) : 0)
async function sync() { if (!detail.value || !token.value || !online.value) return; await flushAttempt(detail.value.attempt.id, { saveAnswer: async (record) => { try { const saved = await $fetch<{ version: number }>(`${config.public.apiBase}/v1/student/attempts/${record.attemptId}/answers/${record.itemId}`, { method: 'PUT', headers: { Authorization: `Bearer ${token.value}` }, body: { answer: record.answer, version: record.version } }); return { kind: 'saved' as const, version: saved.version } } catch (error: any) { if (error?.response?.status === 409) return { kind: 'conflict' as const, current: error.data.current }; return { kind: 'offline' as const } } } }); await refreshSubmit(); syncStatus.value = canSubmit.value ? '已同步' : '需要处理同步冲突' }
async function refreshSubmit() { canSubmit.value = detail.value ? await canSubmitAttempt(detail.value.attempt.id) : false }
const canSubmit = ref(false)
async function saveDraft() { if (!detail.value || !currentItem.value || !principal.value) return; currentItem.value.answer = { value: answer.value }; await queueAnswer({ tenantId: principal.value.tenant_id, userId: principal.value.id, attemptId: detail.value.attempt.id, itemId: currentItem.value.id, answer: currentItem.value.answer, version: currentItem.value.version }); syncStatus.value = '已保存到本机，等待同步'; await sync() }
async function submit() { if (!detail.value || !token.value) return; await sync(); if (!await canSubmitAttempt(detail.value.attempt.id)) return; const key = await getSubmissionKey(detail.value.attempt.id); await $fetch(`${config.public.apiBase}/v1/student/assignments/${detail.value.id}/submit`, { method: 'POST', headers: { Authorization: `Bearer ${token.value}`, 'Idempotency-Key': key } }); syncStatus.value = '已提交' }
onMounted(async () => { if (!token.value) { message.value = '正在等待登录状态…'; return }; try { const [identity, assignment] = await Promise.all([fetchCurrentPrincipal(config.public.apiBase, token.value, $fetch), $fetch<Detail>(`${config.public.apiBase}/v1/student/assignments/${route.params.assignmentId}`, { headers: { Authorization: `Bearer ${token.value}` } })]); principal.value = identity; detail.value = assignment; answer.value = String(currentItem.value?.answer?.value ?? ''); await refreshSubmit(); window.addEventListener('online', () => { online.value = true; sync() }); window.addEventListener('offline', () => online.value = false); window.addEventListener('visibilitychange', () => { if (document.visibilityState === 'hidden') sync() }) } catch { message.value = '暂时无法读取作业。' } })
</script>
